exception ValueError(int value) {
    message: string = "Wrong value="+value to string +" - should be higher than 0";
    value: int = value;
}

$
Block
comment
$

bool is_even(int number){
    return number % 2 == 0;
}

void print_even_if_not_divisible_by_5(int number){
    a = 5;
    while (number > 0) {
        # comment
        if (number % 5 == 0) {
            number = number - 1;
            continue;
        }elif (is_even(number)) {
            number = number - 1;
            continue;
        }else{
            print("x: ", number);
            number = number - 1;
        }
    }
}
void main(){
    try{
        print("Enter value: ");
        a = 3;
        a = "string";
        x = input() to int;
        if (x <= 0){
            throw ValueError(x);
        }
        print_even_if_not_divisible_by_5(x);
    }catch(BaseException e){
        print("Error: ", e.message, "\\n \\t Value=", e.value, e.position, "\\n");
    }
}